### PR TITLE
Merge back pull https://github.com/EOSIO/fc/pull/169/ to 2.0.x, ( std…

### PR DESCRIPTION
**Pull request by softprofe**
Merge back pull https://github.com/EOSIO/fc/pull/169/ to 2.0.x  (std_out does not work in Nodeos logging)

### CODE REVIEW

**Review by heifner — APPROVED** [review]
In the future please use git cherry-pick as it is easier to track changes.

**Comment by softprofe** [comment]
> In the future please use git cherry-pick as it is easier to track changes.

However, git cherry-pick told me the base is different so cherry-pick failed.

**Comment by heifner** [comment]
> However, git cherry-pick told me the base is different so cherry-pick failed.

```
➜  eos-develop git:(log-spam) ✗ cd libraries/fc
➜  fc git:(a4ad789) git checkout eosio-2.0.x
Previous HEAD position was a4ad789 Merge branch 'eosio' into file_copy_norecursive
Branch 'eosio-2.0.x' set up to track remote branch 'eosio-2.0.x' from 'origin'.
Switched to a new branch 'eosio-2.0.x'
➜  fc git:(eosio-2.0.x) git checkout -b tmp
Switched to a new branch 'tmp'
➜  fc git:(tmp) git cherry-pick 4b6855299f5d208bf8c408b7fdc8d251d44b2213
Auto-merging src/log/console_appender.cpp
CONFLICT (content): Merge conflict in src/log/console_appender.cpp
error: could not apply 4b68552... Fix support for stdout
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
➜  fc git:(tmp) ✗ vi src/log/console_appender.cpp
➜  fc git:(tmp) ✗ git add src/log/console_appender.cpp
➜  fc git:(tmp) ✗ git cherry-pick --continue
[tmp a6dceda] Fix support for stdout
 Date: Wed Oct 21 13:11:33 2020 -0500
 1 file changed, 7 insertions(+), 7 deletions(-)
```

**Comment by softprofe** [comment]
I see, thanks. will use this way in future.

**Pull request merged**
